const {chromium,expect}=require('@playwright/test');
const assert=require('node:assert/strict');
const xml=require('./pubmed-fixture.cjs');
(async()=>{
 const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});
 const remote=new Map(),watches=new Map();let fail=false,delayReference=false,releaseReference;
 function snapshot(path){const n=path.split('/').length;return [...remote].filter(([key])=>key.startsWith(path+'/')&&key.split('/').length===n+1).map(([key,data])=>({id:key.split('/').at(-1),data}));}
 async function notify(){for(const[page,subscriptions]of watches)for(const[id,path]of [...subscriptions])await page.evaluate(({id,docs})=>window.receiveCommunity?.(id,docs),{id,docs:snapshot(path)});}
 const adapter=`let next=0;const listeners=new Map();const snap=data=>({exists:()=>data!==null,data:()=>data});export const doc=(_, ...parts)=>({path:parts.join('/')});export const collection=doc;export const query=ref=>ref;export const where=()=>({});export const orderBy=()=>({});export const limit=()=>({});export const serverTimestamp=()=>new Date().toISOString();export const setDoc=async(ref,data)=>window.writeCommunity(ref.path,data);export const getDocs=async()=>({forEach(){}});export const addDoc=()=>{};export const getDocFromServer=async ref=>snap(await window.readCommunity(ref.path));export const runTransaction=async(_,callback)=>{const pending=[];await callback({get:async ref=>snap(await window.readCommunity(ref.path)),set:(ref,data)=>pending.push([ref.path,data])});for(const[path,data]of pending)await window.writeCommunity(path,data);};window.receiveCommunity=(id,docs)=>listeners.get(id)?.({docs:docs.map(doc=>({id:doc.id,data:()=>doc.data,metadata:{hasPendingWrites:false}})),metadata:{fromCache:false}});export const onSnapshot=(ref,...args)=>{const callback=args.find(value=>typeof value==='function');const id=String(++next);listeners.set(id,callback);window.addCommunityWatch(id,ref.path).then(docs=>window.receiveCommunity(id,docs));return()=>{listeners.delete(id);window.removeCommunityWatch(id);};};`;
 async function device(uid,name){
  const context=await browser.newContext({serviceWorkers:'block'});
  await context.addInitScript(({uid,name})=>{localStorage.setItem('clinicalmind.accounts.v1',JSON.stringify({[`${uid}@example.com`]:{name,email:`${uid}@example.com`,authProvider:'google',firebaseUid:uid}}));sessionStorage.setItem('clinicalmind.session.v1',`${uid}@example.com`);},{uid,name});
  await context.route('https://**',route=>route.abort());
  await context.route('**/auth-google.js',route=>route.fulfill({contentType:'text/javascript',body:`export const db={};export const auth={currentUser:{uid:${JSON.stringify(uid)}}};`}));
  await context.route('https://www.gstatic.com/firebasejs/12.19.0/firebase-firestore.js',route=>route.fulfill({contentType:'text/javascript',body:adapter}));
  await context.route('https://eutils.ncbi.nlm.nih.gov/**',route=>{const url=new URL(route.request().url());if(url.pathname.endsWith('esearch.fcgi'))return route.fulfill({contentType:'application/json',body:JSON.stringify({esearchresult:{idlist:[]}})});return route.fulfill({contentType:'application/xml',body:xml(url.searchParams.get('id')==='123'?[{pmid:'123',title:'PubMed linked study',abstract:'Summary'}]:[])});});
  await context.route('https://api.crossref.org/works/**',async route=>{if(delayReference)await new Promise(resolve=>releaseReference=resolve);return route.fulfill({contentType:'application/json',body:JSON.stringify({message:{DOI:'10.1234/test',title:['Crossref study <img src=x onerror=alert(1)>'],author:[{given:'Ana',family:'Researcher'}]}})});});
  const page=await context.newPage(),errors=[];watches.set(page,new Map());page.on('pageerror',e=>errors.push(e.message));
  await page.exposeFunction('readCommunity',path=>remote.get(path)??null);
  await page.exposeFunction('writeCommunity',async(path,data)=>{if(fail)throw Error('permission-denied');remote.set(path,data);await notify();});
  await page.exposeFunction('addCommunityWatch',(id,path)=>{watches.get(page).set(id,path);return snapshot(path);});
  await page.exposeFunction('removeCommunityWatch',id=>watches.get(page).delete(id));
  await page.goto('http://127.0.0.1:8080/');await page.evaluate(({uid,name})=>window.clinicalMindGoogleSuccess({uid,email:`${uid}@example.com`,name}),{uid,name});await page.locator('#sidebarToggle').click();await page.locator('#nav [data-section="Comunidade"]').click();await expect(page.locator('#caseConnection')).toContainText('Comunidade compartilhada');return {page,errors};
 }
 const first=await device('uid-one','Author One'),second=await device('uid-two','Author Two');
 const p=first.page,q=second.page;
 await p.locator('#casePostForm [name="assessment"]').fill('Academic assessment of the simulated case.');await p.locator('#casePostForm [name="plan"]').fill('An evidence-based educational management plan.');await p.locator('#casePostForm [name="reference"]').fill('KDIGO 2024');await p.locator('#casePostForm [data-article-id]').fill('PMID: 123');await p.locator('#casePostForm [data-article-lookup]').click();await expect(p.locator('#casePostForm [data-article-preview]')).toContainText('PubMed linked study');await p.locator('#casePostForm button[type="submit"]').click();await expect(p.locator('#caseStatus')).toContainText('Conduta publicada');
 await expect(q.locator('.case-post:not(.is-demo)')).toHaveCount(1);const caseId=await q.locator('.case-post:not(.is-demo)').getAttribute('data-post-id');assert.equal(remote.get('forum_posts/'+caseId).userId,'uid-one');assert.equal(remote.get('forum_posts/'+caseId).email,undefined);await expect(q.locator('.case-post:not(.is-demo) .community-article')).toContainText('Researcher A');await expect(q.locator('.case-post:not(.is-demo) .community-article a')).toHaveAttribute('href','https://pubmed.ncbi.nlm.nih.gov/123/');
 await q.locator(`.case-post[data-post-id="${caseId}"] [data-vote="supported"]`).click();await expect(p.locator(`.case-post[data-post-id="${caseId}"] [data-vote="supported"] span`)).toHaveText('1');
 await q.locator(`form[data-reply="${caseId}"] input`).fill('A reply from another user.');await q.locator(`form[data-reply="${caseId}"] button`).click();await expect(p.locator(`.case-post[data-post-id="${caseId}"] .reply`)).toContainText('A reply from another user.');
 // A remote update must preserve a reply draft currently being typed.
 await p.locator(`form[data-reply="${caseId}"] input`).fill('Keep this unfinished reply');await q.locator(`.case-post[data-post-id="${caseId}"] [data-vote="citation"]`).click();await expect(p.locator(`form[data-reply="${caseId}"] input`)).toHaveValue('Keep this unfinished reply');
 await p.locator('#openLegacyCommunity').click();await q.locator('#openLegacyCommunity').click();await expect(q.locator('#communityConnection')).toContainText('Comunidade compartilhada');
 await p.locator('#postForm [name="title"]').fill('Shared general discussion');await p.locator('#postForm [name="body"]').fill('A question about interpreting a guideline.');await p.locator('#postForm [data-article-id]').fill('10.1234/test');await p.locator('#postForm [data-article-lookup]').click();await expect(p.locator('#postForm [data-article-preview]')).toContainText('Ana Researcher');await p.locator('#postForm button[type="submit"]').click();await expect(p.locator('#generalPostStatus')).toContainText('Discussão publicada');await expect(q.locator('.community-card h3')).toHaveText('Shared general discussion');
 await expect(q.locator('.community-card .community-article a')).toHaveAttribute('href','https://doi.org/10.1234/test');await expect(q.locator('.community-card .community-article img')).toHaveCount(0);const generalId=await q.locator('.community-card').getAttribute('data-post-id');await q.locator(`form[data-reply="${generalId}"] input`).fill('General forum reply');await q.locator(`form[data-reply="${generalId}"] button`).click();await expect(p.locator('.community-card .reply')).toContainText('General forum reply');await q.locator('[data-like]').click();await expect(p.locator('[data-like]')).toContainText('1 apoio');
 await p.locator('#postForm [data-article-id]').fill('invalid');await p.locator('#postForm [data-article-lookup]').click();await expect(p.locator('#postForm [data-article-status]')).toContainText('válido');await p.locator('#postForm [data-article-id]').fill('999');await p.locator('#postForm [data-article-lookup]').click();await expect(p.locator('#postForm [data-article-status]')).toContainText('não encontrado');await p.locator('#postForm [data-article-id]').fill('123');await p.locator('#postForm [data-article-lookup]').click();await expect(p.locator('#postForm [data-article-preview]')).toContainText('PubMed linked study');delayReference=true;await p.locator('#postForm [data-article-id]').fill('10.1234/test');await p.locator('#postForm [data-article-lookup]').click();await expect(p.locator('#postForm button[type="submit"]')).toBeDisabled();await expect.poll(()=>Boolean(releaseReference)).toBe(true);await p.locator('#postForm [data-article-id]').fill('123');delayReference=false;releaseReference();await p.locator('#postForm [data-article-lookup]').click();await expect(p.locator('#postForm [data-article-preview]')).toContainText('PubMed linked study');await p.locator('#postForm [data-article-id]').fill('10.1234/test');await expect(p.locator('#postForm [data-article-preview]')).toBeEmpty();await p.locator('#postForm [data-article-lookup]').click();await expect(p.locator('#postForm [data-article-preview]')).toContainText('Crossref study');
 fail=true;await p.locator('#postForm [name="title"]').fill('Unpublished draft');await p.locator('#postForm [name="body"]').fill('Keep this when the cloud rejects the write.');await p.locator('#postForm button[type="submit"]').click();await expect(p.locator('#generalPostStatus')).toContainText('Não foi possível publicar');await expect(p.locator('#postForm [name="body"]')).toHaveValue('Keep this when the cloud rejects the write.');await expect(q.locator('.community-card')).toHaveCount(1);await expect(p.locator('#postForm [data-article-preview]')).toContainText('Crossref study');fail=false;
 assert.deepEqual(first.errors,[]);assert.deepEqual(second.errors,[]);console.log('Browser passed: two users share clinical and general posts, replies, votes, and likes in real time; drafts and articles survive failed writes; PMID/DOI metadata, canonical links, safe rendering and failed lookups. Firestore, PubMed and Crossref simulated.');watches.clear();await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
