const {chromium,expect}=require('@playwright/test');
const assert=require('node:assert/strict');
const xml=require('./pubmed-fixture.cjs');
(async()=>{
 const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});const context=await browser.newContext({...(process.env.PROTOCOLUM_MOBILE?{viewport:{width:390,height:844}}:{}),serviceWorkers:'block'});let mode='offline';const requests=[];
 const publications={123:{pmid:'123',guideline:true,title:'Online guideline & care',journal:'Live Guideline Journal',abstract:'Evidence obtained online. <img src=x onerror=alert(1)>'},456:{pmid:'456',title:'Remote randomized trial',journal:'Trial Journal'},789:{pmid:'789',title:'Older saved reference',year:2020,journal:'Older Journal'},987:{pmid:'987',guideline:true,title:'Kidney treatment publication',journal:'Nephrology Internet Journal'}};
 await context.addInitScript(()=>{localStorage.setItem('clinicalmind.accounts.v1',JSON.stringify({'local@example.com':{email:'local@example.com',name:'Local'}}));sessionStorage.setItem('clinicalmind.session.v1','local@example.com');localStorage.setItem('clinicalmind.pubmed.library.v1',JSON.stringify({checkedAt:Date.now(),records:[{id:'pubmed-999',title:'Stale cached title'}]}));localStorage.setItem('clinicalmind.favorites.local@example.com','["pubmed-789"]');});
 await context.route('https://**',route=>route.abort());
 await context.route('**/auth-google.js',route=>route.fulfill({contentType:'text/javascript',body:'export const db=null;export const auth=null;'}));
 await context.route('https://eutils.ncbi.nlm.nih.gov/**',async route=>{
  const url=new URL(route.request().url());requests.push(url);if(mode==='offline')return route.fulfill({status:503,body:'Unavailable'});
  if(url.pathname.endsWith('esearch.fcgi')){const renal=url.searchParams.get('term').includes('renal treatment'),guideline=url.searchParams.get('term').includes('Practice Guideline');return route.fulfill({contentType:'application/json',body:JSON.stringify({esearchresult:{idlist:renal?(guideline?['987']:[]):guideline?['123']:['456']}})});}
  const ids=url.searchParams.get('id').split(',');return route.fulfill({contentType:'application/xml',body:mode==='malformed'?'<invalid>':xml(ids.map(id=>publications[id]).filter(Boolean))});
 });
 const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:8080/');await expect(page.locator('#libraryAutoStatus')).toHaveAttribute('data-state','error');await expect(page.locator('.item[data-title]')).toHaveCount(0);assert.ok(!(await page.locator('body').innerText()).includes('Stale cached title'));
 mode='online';await page.locator('#refreshLibrary').click();await expect(page.locator('#libraryAutoStatus')).toHaveAttribute('data-state','ready');await expect(page.locator('[data-title="Online guideline & care"]')).toBeVisible();assert.ok(requests.some(url=>url.searchParams.get('id')?.includes('789')));await expect(page.locator('#onlineReferenceSources')).toContainText('Live Guideline Journal');assert.equal(await page.locator('#onlineReferenceSources a').first().getAttribute('href'),'https://pubmed.ncbi.nlm.nih.gov/123/');
 await page.locator('[data-title="Online guideline & care"]').click();await expect(page.locator('#readerSummary')).toContainText('Evidence obtained online. <img src=x onerror=alert(1)>');await expect(page.locator('#readerSummary img')).toHaveCount(0);await page.evaluate(()=>document.getElementById('detailOverlay').style.display='none');
 await page.locator('#advanced').click();await expect(page.locator('#pubmedYearFrom')).toBeFocused();await page.locator('#pubmedYearFrom').fill('2020');await page.locator('#pubmedYearTo').fill('2024');await page.locator('#pubmedStudyType').selectOption('systematic');await page.locator('#pubmedFullText').selectOption('free');
 const beforeFiltered=requests.length;await page.locator('#applyFilters').click();await expect(page.locator('#applyFilters')).toBeEnabled();const filtered=requests.slice(beforeFiltered).filter(url=>url.pathname.endsWith('esearch.fcgi'));assert.equal(filtered.length,1);const query=filtered[0].searchParams.get('term');assert.ok(query.includes('"Systematic Review"[Publication Type]'));assert.ok(query.includes('"2020/01/01"[Date - Publication]'));assert.ok(query.includes('"2024/12/31"[Date - Publication]'));assert.ok(query.includes('free full text[sb]'));assert.equal(filtered[0].searchParams.has('reldate'),false);await expect(page.locator('[data-title="Older saved reference"]')).toHaveCount(0);
 await page.locator('#advanced').click();await page.locator('#pubmedYearFrom').fill('2025');const beforeInvalid=requests.length;await page.locator('#applyFilters').click();await expect(page.locator('#libraryAutoStatus')).toContainText('ano inicial');assert.equal(requests.length,beforeInvalid);
 await page.locator('#pubmedYearFrom').fill('2020');await page.locator('#pubmedFullText').selectOption('full');await page.locator('#pubmedStudyType').selectOption('all');const beforeAll=requests.length;await page.locator('#applyFilters').click();await expect(page.locator('#applyFilters')).toBeEnabled();const all=requests.slice(beforeAll).find(url=>url.pathname.endsWith('esearch.fcgi')).searchParams.get('term');assert.ok(all.includes('full text[sb]'));assert.ok(!all.includes('free full text[sb]'));assert.ok(!all.includes('[Publication Type]'));
 await page.locator('#advanced').click();await page.locator('#pubmedYearTo').fill('2023');await page.locator('#drawerBackdrop').click({position:{x:page.viewportSize().width-4,y:100}});mode='offline';const beforeRefresh=requests.length;await page.locator('#refreshLibrary').click();await expect(page.locator('#libraryAutoStatus')).toHaveAttribute('data-state','error');assert.ok(requests.slice(beforeRefresh).find(url=>url.pathname.endsWith('esearch.fcgi')).searchParams.get('term').includes('"2024/12/31"'));mode='online';await page.locator('#showAll').click();await expect(page.locator('#applyFilters')).toBeEnabled();await expect(page.locator('#pubmedYearFrom')).toHaveValue('');await expect(page.locator('#pubmedYearTo')).toHaveValue('');await expect(page.locator('#pubmedStudyType')).toHaveValue('recent');await expect(page.locator('#pubmedFullText')).toHaveValue('any');
 await page.locator('#search').fill('renal treatment');await page.locator('#searchOnlineLibrary').click();await expect(page.locator('[data-title="Kidney treatment publication"]')).toBeVisible();await expect(page.locator('#onlineReferenceSources')).toContainText('Nephrology Internet Journal');await expect(page.locator('[data-title="Online guideline & care"]')).toHaveCount(0);
 await page.locator('#advanced').click();await page.locator('#pubmedYearFrom').fill('2025');await page.locator('#pubmedYearTo').fill('2020');await page.keyboard.press('Escape');
 await page.locator('#search').fill('789');await page.locator('#searchOnlineLibrary').click();await expect(page.locator('[data-title="Older saved reference"]')).toBeVisible();await expect(page.locator('#nav [data-section="Literatura"]')).toHaveClass(/active/);
 await expect(page.locator('#libraryAutoStatus')).toContainText('filtros não aplicados');await page.locator('#advanced').click();await page.locator('#pubmedYearFrom').fill('');await page.locator('#pubmedYearTo').fill('');await page.keyboard.press('Escape');
 await page.locator('#search').fill('renal treatment');await page.locator('#searchOnlineLibrary').click();await expect(page.locator('[data-title="Kidney treatment publication"]')).toBeVisible();
 mode='malformed';await page.locator('#refreshLibrary').click();await expect(page.locator('#libraryAutoStatus')).toHaveAttribute('data-state','error');await expect(page.locator('[data-title="Kidney treatment publication"]')).toBeVisible();await expect(page.locator('#libraryAutoStatus')).toContainText('última consulta online');assert.deepEqual(errors,[]);
 console.log('Browser passed: no embedded/cache fallback, online guidelines and sources, favorite retrieval, safe abstracts, remote search, malformed-response feedback, year/type/full-text queries, invalid ranges, retry and clearing filters. PubMed simulated.');await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
