const {chromium,expect}=require('@playwright/test');
const assert=require('node:assert/strict');
const xml=require('./pubmed-fixture.cjs');
(async()=>{
 const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});
 const documents=new Map([['private_profiles/me',{name:'Ana',bio:'Bio original',city:'São Paulo',sharing:{published:false,autoUpdate:true,visible:[]}}],['private_study/me',{favorites:[]}]]),watches=new Map();
 async function notify(){for(const[page,subscriptions]of watches)for(const[id,path]of [...subscriptions])await page.evaluate(({id,data})=>window.receiveLive(id,data),{id,data:documents.get(path)||null});}
 async function device(){
  const context=await browser.newContext({serviceWorkers:'block'});
  await context.addInitScript(()=>{localStorage.setItem('clinicalmind.accounts.v1',JSON.stringify({'ana@example.com':{name:'Ana',email:'ana@example.com',authProvider:'google',firebaseUid:'me'}}));sessionStorage.setItem('clinicalmind.session.v1','ana@example.com');});
  await context.route('https://**',route=>route.abort());await context.route('**/auth-google.js',route=>route.fulfill({contentType:'text/javascript',body:"export const db={};export const auth={currentUser:{uid:'me'}};"}));
  await context.route('https://eutils.ncbi.nlm.nih.gov/**',route=>{const url=new URL(route.request().url());if(url.pathname.endsWith('esearch.fcgi'))return route.fulfill({contentType:'application/json',body:JSON.stringify({esearchresult:{idlist:['123','456']}})});return route.fulfill({contentType:'application/xml',body:xml(url.searchParams.get('id').split(',').map(pmid=>({pmid,guideline:true,title:'Live reference '+pmid})))});});
  await context.route('https://www.gstatic.com/firebasejs/12.19.0/firebase-firestore.js',route=>route.fulfill({contentType:'text/javascript',body:`
  const listeners=new Map();let sequence=0;const snapshot=data=>({exists:()=>data!==null,data:()=>data,metadata:{fromCache:false,hasPendingWrites:false}});
  export const doc=(db,...parts)=>({path:parts.join('/'),firestore:db});export const collection=(db,...parts)=>({...doc(db,...parts),collection:true});export const query=ref=>ref;export const where=()=>({});export const orderBy=()=>({});export const startAt=()=>({});export const endAt=()=>({});export const limit=()=>({});
  export const getDocFromServer=async ref=>snapshot(await window.readLive(ref.path));export const getDoc=getDocFromServer;export const getDocs=async()=>({docs:[],forEach(){}});export const setDoc=async(ref,data,options)=>window.commitLive([{ref,data,options}]);export const serverTimestamp=()=>0;export const addDoc=()=>{};
  export const runTransaction=async(_,callback)=>{const operations=[];const value=await callback({get:getDoc,set:(ref,data,options)=>operations.push({ref,data,options}),delete:ref=>operations.push({ref,remove:true})});await window.commitLive(operations);return value;};
  window.receiveLive=(id,data)=>listeners.get(id)?.next(snapshot(data));window.failLive=path=>{for(const value of listeners.values())if(value.path===path)value.error?.(Error('offline'));};
  export const onSnapshot=(ref,...args)=>{const callbacks=args.filter(value=>typeof value==='function');if(ref.collection){callbacks[0]({docs:[],metadata:{fromCache:false}});return()=>{};}const id=String(++sequence);listeners.set(id,{path:ref.path,next:callbacks[0],error:callbacks[1]});window.watchLive(id,ref.path).then(data=>window.receiveLive(id,data));return()=>{listeners.delete(id);window.unwatchLive(id);};};
  `}));
  const page=await context.newPage(),errors=[];watches.set(page,new Map());page.on('pageerror',error=>errors.push(error.message));await page.exposeFunction('readLive',path=>documents.get(path)||null);await page.exposeFunction('watchLive',(id,path)=>{watches.get(page).set(id,path);return documents.get(path)||null;});await page.exposeFunction('unwatchLive',id=>watches.get(page).delete(id));await page.exposeFunction('commitLive',async operations=>{for(const op of operations){const path=op.ref.path;if(op.remove)documents.delete(path);else documents.set(path,op.options?.merge?{...documents.get(path),...op.data}:op.data);}await notify();});
  await page.goto('http://127.0.0.1:8080/');await page.evaluate(async()=>{window.clinicalMindGoogleSuccess({uid:'me',email:'ana@example.com',name:'Ana'});const study=await import('/study-sync.js');await study.loadFavorites(window.clinicalMindCurrentUser());});await expect(page.locator('#libraryAutoStatus')).toHaveAttribute('data-state','ready');await page.locator('#sidebarToggle').click();await page.locator('#nav [data-section="Perfil"]').click();await expect(page.locator('#profileBio')).toHaveValue(documents.get('private_profiles/me').bio);return {page,errors};
 }
 const first=await device(),second=await device(),p=first.page,q=second.page;
 await q.locator('.academic-editor').filter({has:q.locator('#professionalProfile')}).locator('summary').click();await q.locator('#profileBio').fill('Bio de outro dispositivo');await q.locator('#professionalProfile button').click();await expect(p.locator('#profileBio')).toHaveValue('Bio de outro dispositivo');
 await q.locator('#profileName').fill('Ana atualizada');await q.locator('#profileForm button').click();await expect(p.locator('.profile-summary h3')).toHaveText('Ana atualizada');
 await p.locator('.academic-editor').filter({has:p.locator('#professionalProfile')}).locator('summary').click();await p.locator('#profileBio').fill('Meu rascunho');await q.locator('#profileCity').fill('Campinas');await q.locator('#professionalProfile button').click();await expect(p.locator('.profile-live-notice')).toContainText('outro dispositivo');await expect(p.locator('#profileBio')).toHaveValue('Meu rascunho');await p.locator('#professionalProfile button').click();await expect(p.locator('#profileSyncMessage')).toHaveText('Salvo na nuvem.');assert.equal(documents.get('private_profiles/me').city,'Campinas');assert.equal(documents.get('private_profiles/me').bio,'Meu rascunho');await expect(p.locator('#profileCity')).toHaveValue('Campinas');await expect(q.locator('#profileBio')).toHaveValue('Meu rascunho');
 // Listener errors can be retried without discarding an active draft.
 await p.locator('#profileBio').fill('Rascunho mantido');await p.evaluate(()=>window.failLive('private_profiles/me'));await expect(p.locator('.profile-live-notice')).toContainText('interrompida');await p.locator('.profile-live-notice button').click();await expect(p.locator('#profileBio')).toHaveValue('Rascunho mantido');await expect(p.locator('.profile-live-notice')).toBeHidden();
 await p.locator('#sidebarToggle').click();await p.locator('#nav [data-section="Diretrizes"]').click();await p.locator('[data-title="Live reference 123"]').click();await expect(p.locator('#readerFavorite')).toHaveAttribute('aria-pressed','false');await q.evaluate(async()=>{const study=await import('/study-sync.js');await study.toggleFavorite(window.clinicalMindCurrentUser(),'pubmed-123');});await expect(p.locator('#readerFavorite')).toHaveAttribute('aria-pressed','true');await q.evaluate(async()=>{const study=await import('/study-sync.js');await study.toggleFavorite(window.clinicalMindCurrentUser(),'pubmed-123');});await expect(p.locator('#readerFavorite')).toHaveAttribute('aria-pressed','false');await p.evaluate(()=>document.getElementById('detailOverlay').style.display='none');await p.locator('#sidebarToggle').click();await p.locator('#nav [data-section="Favoritos"]').click();await q.evaluate(async()=>{const study=await import('/study-sync.js');await study.toggleFavorite(window.clinicalMindCurrentUser(),'pubmed-456');});await expect(p.locator('[data-title="Live reference 456"]')).toBeVisible();
 await p.evaluate(()=>window.failLive('private_study/me'));await expect(p.locator('#favoriteLiveNotice')).toBeVisible();await p.locator('#favoriteLiveNotice button').click();await expect(p.locator('#favoriteLiveNotice')).toBeHidden();
 await p.evaluate(async()=>{const profile=await import('/profile-store.js'),study=await import('/study-sync.js');profile.resetProfileSync();study.resetStudySync();window.clinicalMindGoogleSignOutSuccess();});await expect.poll(()=>watches.get(p).size).toBe(0);assert.deepEqual(first.errors,[]);assert.deepEqual(second.errors,[]);
 console.log('Browser passed: two open devices receive profile/name and favorite changes, drafts are preserved, unchanged fields merge, reader and list update, reconnection and sign-out cleanup. Firestore and PubMed simulated.');watches.clear();await browser.close();
})().catch(error=>{console.error(error);process.exit(1);});
